# -*- coding: utf-8 -*-
"""Insuranceipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HxeNhZnJ0CmCTLpcGkIilsaG9PYoBM4W
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn import metrics

insurance_dataset=pd.read_csv('/content/insurance.csv')

insurance_dataset.head()

insurance_dataset.shape

insurance_dataset.isnull().sum()

insurance_dataset.describe()

insurance_dataset.info()

sns.set()
plt.figure(figsize=(7,5))
sns.distplot(insurance_dataset['age'])
plt.show()

plt.figure(figsize=(6,6))
sns.countplot(x='sex',data=insurance_dataset)
plt.show()

insurance_dataset['sex'].value_counts()

plt.figure(figsize=(6,6))
sns.distplot(insurance_dataset['bmi'])
plt.show()

plt.figure(figsize=(6,6))
sns.countplot(x='children',data=insurance_dataset)
plt.title('children col')
plt.show()

insurance_dataset['children'].value_counts()

plt.figure(figsize=(6,6))
sns.countplot(x='smoker',data=insurance_dataset)
plt.show()

insurance_dataset['smoker'].value_counts()

plt.figure(figsize=(6,6))
sns.countplot(x='region',data=insurance_dataset)
plt.show()

insurance_dataset.value_counts('region')

plt.figure(figsize=(6,6))
sns.distplot(insurance_dataset['charges'])
plt.show()

#Encoding the categorical features
insurance_dataset.replace({'sex':{'male':0,'female':1},'smoker':{'yes':0,'no':1}},inplace=True)

insurance_dataset.replace({'region':{'southeast':0,'southwest':1,'northeast':2,'northwest':3}},inplace=True)

insurance_dataset.replace({'smoker':{'yes':1,'no': 0}}, inplace=True)

#spliting the features and target
X=insurance_dataset.drop(columns='charges',axis=1)
Y=insurance_dataset['charges']

print(X)

print(Y)

#split into trainning and testing data
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=2)

print(X.shape,X_train.shape,X_test.shape)

#model traing
#linear regration model
regressor=LinearRegression()

regressor.fit(X_train,Y_train)

#prediction on trainning data
training_data_prediction=regressor.predict(X_train)

#R square value
r2_train = metrics.r2_score(Y_train, training_data_prediction)
print('R squared vale : ', r2_train)

test_data_prediction=regressor.predict(X_test)

r2_test = metrics.r2_score(Y_test, test_data_prediction)
print('R squared vale : ', r2_test)

input_data = (31,1,25.74,0,1,0)

# changing input_data to a numpy array
input_data_as_numpy_array = np.asarray(input_data)

# reshape the array
input_data_reshaped = input_data_as_numpy_array.reshape(1,-1)

prediction = regressor.predict(input_data_reshaped)
print(prediction)

print('The insurance cost is USD ', prediction[0])

