# -*- coding: utf-8 -*-
"""Data standardization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TVqLvhg-zHKDaccqkALvONY4nhBpr7nA

Data standardization
the process of standarding the data to a common format and common range
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn.datasets
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split#help us to split our data into traning data

#loading the data set
dataset=sklearn.datasets.load_breast_cancer()
print(dataset)

#loading data to pd dataframe
df=pd.DataFrame(dataset.data,columns=dataset.feature_names)

df.head()

df.shape

x=df
y=dataset.target

print(x)

print(y)

#splitting the data into training data and test data
X_train, X_test, Y_train, Y_test = train_test_split(x, y, test_size=0.2, random_state=3)#0.2 test size is %of data

print(x.shape, X_train.shape, X_test.shape)

#Standardize the data
print(dataset.data.std())

scaler=StandardScaler()

scaler.fit(X_train)

X_train_standardized=scaler.transform(X_train)

print(X_train_standardized.std())

print(X_train_standardized)

X_test_standardized=scaler.transform(X_test)

print(X_test_standardized.std())

print(X_test_standardized)

