# -*- coding: utf-8 -*-
"""matplotlib_tutorial.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yswxHgznypg-KpBxeN8lCNH-lDZUYjQ4
"""

#import
import matplotlib.pyplot as plt

#import numpy to get data for our plot
import numpy as np

x=np.linspace(0, 10, 100)
y=np.sin(x)
z=np.cos(x)

print(x)

print(y)

print(z)



"""plotting the data"""

#sine wave
plt.plot(x, y)
plt.show()

#cosine wave
plt.plot(x, z)
plt.show()

# adding title x axis y axis labels
plt.plot(x, y)
plt.xlabel('angle')
plt.ylabel('sine value')
plt.title("sine-wave")
plt.show()

#ploting a parabola
x=np.linspace(-10, 10, 20)
y=x**2
plt.plot(x, y)
plt.show()

plt.plot(x, y, 'r+')# plot the parabola in red and plus
plt.show()

plt.plot(x, y,'g.')#green color and .
plt.show()

plt.plot(x, y, 'rx')
plt.show()

x=np.linspace(-5,5, 50)
plt.plot(x, np.sin(x), 'g-')
plt.plot(x, np.cos(x), 'r--')
plt.show()



"""Bar plot"""

fig=plt.figure()
ax=fig.add_axes([0, 0, 1, 1])
languages=['english', 'french', 'spanish', 'german', 'hindi']
people=[100, 50, 150, 40, 200]
ax.bar(languages, people)
plt.xlabel('languages')
plt.ylabel('no of people')
plt.show()



"""pychart"""

fig1=plt.figure()
ax=fig1.add_axes([0,0,1, 1])
languages=['english', 'french', 'spanish', 'german', 'hindi']
people=[100, 50, 150, 40, 200]
ax.pie(people, labels=languages, autopct='%1.1f%%')
plt.show()

"""scatter plot"""

x=np.linspace(0, 10, 30)
y=np.sin(x)
z=np.cos(x)
fig2=plt.figure()
ax=fig2.add_axes([0,0,1,1])
ax.scatter(x, y, color='g')
ax.scatter(x, z, color='b')
plt.show()

"""3d scattred plot"""

fig3=plt.figure()
ax=plt.axes(projection='3d')
z=20* np.random.random(100)
x=np.sin(z)
y=np.cos(z)
ax.scatter(x, y, z, c=z, cmap='Blues')
plt.show()

