# -*- coding: utf-8 -*-
"""Numerical_data_preprocessing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1auF7YqhQda4wr2-Je8AP9B8P2B_3X-Q_
"""

import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

#data collection and preprocessing
diabetes_data=pd.read_csv('diabetes.csv')
diabetes_data.head()

diabetes_data.shape

diabetes_data.describe()

#separting features and target
x=diabetes_data.drop(columns='Outcome',axis=1)
y=diabetes_data['Outcome']

print(x)

print(y)

#standardise the data
scaler=StandardScaler()
scaler.fit(x)
standardise_data=scaler.transform(x)

print(standardise_data)

X=standardise_data
Y=diabetes_data['Outcome']

print(Y)

#spliting the data set into training and testing data
X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size = 0.2, stratify=Y, random_state=2)

print(X.shape, X_train.shape, X_test.shape)

print(X_train)

