# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YuOAgoi_lEgvW8mMIky9_y_ymiO73lJi
"""

print("hello world")

import numpy as np
a=np.array([1, 2,3,4])
print(type(a))
print(a)

b=np.array([[1,2 ,3],[4, 5,6]])
print(b)
print(b.shape)

"""initial placeholders in numpy arrays

"""

#create an array with all values zero
x=np.zeros((4, 5))
print(x)

y=np.ones((3, 4))
print(y)

#array with specific value
z=np.full((3, 3),5)
print(z)

# creating an identity matrix
a=np.eye(3)
print(a)

#create an array with random values
b=np.random.random((3, 4))
print(b)

#create an array with random values in a range
c=np.random.randint(10, 100, (3, 4))
print(c)

#array with evenly spaced
d=np.linspace(10, 30, 4)
print(d)

#array with evenly spaced value specifying space
e=np.arange(10, 30, 5)
print(e)

list2=[10, 20, 30 , 40, 50]
np_array=np.asarray(list2)
print(type(np_array))

"""Analysing a numpy array

"""

c=np.random.randint(10, 90, (5, 5))
print(c)
print(c.shape)
print(c.ndim)#no of dimension
print(c.size)#no of elements in the array
print(c.dtype)#checks the data type of values in array

"""Mathematical operations on np arrays"""

a=np.random.randint(0, 10,(3, 3))
b=np.random.randint(10, 20, (3, 3))
print(f"a={a}")
print(f"b={b}")
print(a+b)
print(a-b)
print(a*b)
print(a/b)

print(np.add(a, b))
print(np.subtract(a, b))
print(np.multiply(a, b))
print(np.divide(a, b))

"""Array manipulation

"""

array= np.random.randint(0, 10,(2,3))
print(array)
trans=np.transpose(array)
print(trans)
trans2=array.T
print(trans2)

from google.colab import drive
drive.mount('/content/drive')