# -*- coding: utf-8 -*-
"""Heart_disease.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1t0XrgG6Pd1iL544--Ie7RS6TlDdWSPsX
"""

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

#data collection and processing
heart_data=pd.read_csv('data.csv')

heart_data.head()

heart_data.shape

heart_data.tail()

heart_data.info()

#checking for missing values
heart_data.isnull().sum()

#stastical measure of the data
heart_data.describe()

#checking the distribution of target variable
heart_data['target'].value_counts()

#1 means defective heart and 0 represents good heart
#spliting the features and target
X=heart_data.drop(columns='target',axis=1)
Y=heart_data['target']
#

print(X)

print(Y)

#split into train and testing data
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,stratify=Y,random_state=2)

print(X.shape,X_train.shape,X_test.shape)

#model trainning
model=LogisticRegression()

model.fit(X_train, Y_train)

#model evaluation
#accuracy on training data
X_train_prediction=model.predict(X_train)
training_data_accuracy=accuracy_score(X_train_prediction,Y_train)

print("Accuracy on traing data:", training_data_accuracy)

#Acurracy on test data
X_test_prediction=model.predict(X_test)
test_data_accuracy=accuracy_score(X_test_prediction,Y_test)

print("Accuracy on test data:", test_data_accuracy)

#building a predictive system
input_data=(41,0,1,130,204,0,0,172,0,1.4,2,0,2)
#change the input data to a numpy array
input_data_as_numpy_array=np.array(input_data)
#reshape the numpy array as we are predicting for only one instance
input_data_reshaped=input_data_as_numpy_array.reshape(1,-1)
prediction=model.predict(input_data_reshaped)
print(prediction)
if(prediction[0]==0):
    print("The person does not have a heart disease")
else:
    print("The person has heart disease")
#

