# -*- coding: utf-8 -*-
"""Calories_burn.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uHkxCAsPtlNPE_orkDwv3CnD8I1sbYYu
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')
from sklearn.model_selection import train_test_split
from xgboost import XGBRegressor
from sklearn import metrics

#data collection and processing
#loading the data to pandas dataframe
calories=pd.read_csv('calories.csv')
exercise=pd.read_csv('exercise.csv')

calories.head()

exercise.head()

#combining the two dataframe
calories_data=pd.concat([exercise,calories['Calories']],axis=1)

#checking the num of rows and cols
calories_data.shape

calories_data.info()

calories_data['Gender'] = calories_data['Gender'].map({'male': 0, 'female': 1})
#checking for missing values
calories_data.isnull().sum()

"""Data analysis

"""

#get some statisticle measure
calories_data.describe()

#Data visualisation
sns.set()

#ploting the gender column in count plot
sns.countplot(calories_data['Gender'])

#finding the distribution of age column
sns.distplot(calories_data['Age'])

#finding the distribution of height
sns.distplot(calories_data['Height'])

#find the distribution of "weight" column
sns.distplot(calories_data['Weight'])

sns.distplot(calories_data['Duration'])

#finding the corellation with dataset
calories_data.replace({"Gender":{'male':0,'female':1}}, inplace=True)
correlation = calories_data.corr()

#constructing the heatmap to understand the correlation
plt.figure(figsize=(10,10))
sns.heatmap(correlation,cbar=True,square=True,fmt='.1f',annot=True,annot_kws={'size':8},cmap='Blues')

X = calories_data.drop(columns=['User_ID','Calories'], axis=1)
Y = calories_data['Calories']

print(X)

print(Y)

#split the data into training and test data
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=2)

print(X.shape, X_train.shape, X_test.shape)



"""Model Training
XGBOOSt Regressor

"""

#loading the model
model = XGBRegressor()

#training the model with X_train
model.fit(X_train, Y_train)



"""Prediction on test Data

"""

test_data_prediction=model.predict(X_test)

print(test_data_prediction)

"""Mean Absolute Error"""

mae=metrics.mean_absolute_error(Y_test,test_data_prediction)

print("mean Absolute Error=", mae)

