# -*- coding: utf-8 -*-
"""Untitled

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y5fnTC-isyMaGetJqdd-qJy14lm5IcdK
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

wine_data=pd.read_csv('winequality-red.csv')

wine_data.shape

wine_data.head()

#checking for missing values
wine_data.isnull().sum()

#data anlysis
wine_data.describe()

#number of values for each quality
sns.catplot(x='quality',data=wine_data,kind='count')

#volatile acidity vs quality
plot=plt.figure(figsize=(5,5))
sns.barplot(x='quality',y='volatile acidity',data=wine_data)

#citric acid vs quality
plot=plt.figure(figsize=(5,5))
sns.barplot(x='quality',y='citric acid',data=wine_data)

#correlation
correlation=wine_data.corr()

#constructing a heatmap to understand the correlation

plt.figure(figsize=(10,10))
sns.heatmap(correlation,cbar=True,square=True,fmt='.1f',annot=True,annot_kws={'size':8},cmap='Blues')

#Data preprocessing
#separate data and lebels
X=wine_data.drop('quality',axis=1)
Y=wine_data['quality'].apply(lambda y_value: 1 if y_value>=7 else 0)

print(X)

print(Y)

#lebel binarizaton
Y=wine_data['quality'].apply(lambda y_value: 1 if y_value>=7 else 0)

print(Y)

#split data into traing and testing data
X_train, X_test, Y_train, Y_test=train_test_split(X,Y,test_size=0.2,random_state=2)

print(X.shape,X_train.shape,X_test.shape)

print(Y.shape,Y_train.shape,Y_test.shape)

#model training
model=RandomForestClassifier()

model.fit(X_train,Y_train)

#accuracy on test data
X_test_prediction=model.predict(X_test)
test_data_accuracy=accuracy_score(X_test_prediction,Y_test)

print("Accuracy:", test_data_accuracy)

input_data = (7.5,0.5,0.36,6.1,0.071,17.0,102.0,0.9978,3.35,0.8,10.5)

# changing the input data to a numpy array
input_data_as_numpy_array = np.asarray(input_data)

# reshape the data as we are predicting the label for only one instance
input_data_reshaped = input_data_as_numpy_array.reshape(1,-1)

prediction = model.predict(input_data_reshaped)
print(prediction)

if (prediction[0]==1):
  print('Good Quality Wine')
else:
  print('Bad Quality Wine')

